ALTER TABLE public."Event" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Team" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Question" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."GameState" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."TeamAnswer" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."LifelineUsage" ENABLE ROW LEVEL SECURITY;
